// Automatically generated by astro-icon
// d0196fd18b9d03393100acdc8ce8540cb3c76d902d79b09877b4357870bec6a6

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "affiliate"
		| "de"
		| "en"
		| "github"
		| "grid"
		| "infra"
		| "learn"
		| "linkedin"
		| "opensource"
		| "server_power"
		| "solar"
		| "solar_with_power"
		| "steam"
		| "telegram"
		| "twitter"
		| "website"
		| "x";
}